<?php 
//Total  Feedback Seller
$totalSellerPositive = Mage::getModel('seller/feedbackseller')->getCollection()
						->addFieldToFilter('seller_id', array('eq' => $sellerId))
						->addFieldToFilter('feedback', array('eq' => 1));
						
$totalSellerNigative = Mage::getModel('seller/feedbackseller')->getCollection()
->addFieldToFilter('seller_id', array('eq' => $sellerId))
->addFieldToFilter('feedback', array('eq' => 2));

//Total  Feedback Buyer
$totalBuyerPositive = Mage::getModel('seller/feedbackbuyer')->getCollection()
->addFieldToFilter('buyer_id', array('eq' => $sellerId))
->addFieldToFilter('feedback', array('eq' => 1));

$totalBuyerNigative = Mage::getModel('seller/feedbackbuyer')->getCollection()
->addFieldToFilter('buyer_id', array('eq' => $sellerId))
->addFieldToFilter('feedback', array('eq' => 2));

?>
<div class="block seller-sidebar">
	<div class="block-title">
		<strong>
			<span><?php echo $this->__('Seller Details'); ?></span>
		</strong>
	</div>
	<div class="block-content">
	<?php
	$_product = Mage::getModel('catalog/product')->load(Mage::registry('current_product')->getId());
	if ($_product->getSellerId())
	{
		$seller = Mage::getModel('customer/customer')->load($_product->getSellerId());
		$write = Mage::getSingleton('core/resource')->getConnection('core_write');
		$readresult=$write->query("SELECT ((SUM(`item_desc`) + SUM(`price`) + SUM(`ship`) + SUM(`communication`)) / count(*)) / 5 as sellerfeedback from jordanshopper_feedback_seller where seller_id = " . $_product->getSellerId());
		$sellerFeedback = $readresult->fetch();
		$sellerFeedback = ceil($sellerFeedback['sellerfeedback']);
		$orderCount = Mage::getModel('sales/order')->getCollection()
		->addFieldToFilter('customer_id', array('eq' => $_product->getSellerId()))
		->getSize();
			
		?>
	<div style="width: 200px;">
		<h2>
			<?php echo $seller->getUsername();?>
			<span style="color: red; font-size: 14px"><a
				href="<?php echo $this->getUrl('seller/rating/list', array('id' => $_product->getSellerId())) ?>">(<?php echo $totalSellerPositive->count() + $totalSellerNigative->count() + $totalBuyerPositive->count() + $totalBuyerNigative->count() ?>)
			</a>
			</span>
		</h2>
	</div>
	<div style="width: 200px;">
		<span class="rating"> <?php for($feedback=0; $feedback < $sellerFeedback; $feedback++) { ?>
			<input type="radio"
			class="rating-input validate-one-required-by-name"
			id="rating-input-1-5-<?php echo $_product->getId() ?>"
			name="<?php echo $_product->getId() ?>" value="5" checked="checked"
			disabled> <label
			for="rating-input-1-5-<?php echo $_product->getId() ?>"
			class="rating-star"></label> <?php } ?>
		</span>
	</div>
	<?php } ?>
	<?php if ($_product->getContactMe()) {
		if (Mage::getSingleton('customer/session')->isLoggedIn()) {
	?>
	<p><a href="#" onclick="javascript:document.getElementById('seller-contact-me').setAttribute('class','')" class="link-compare"><?php echo $this->__('Contact seller for this item')?></a></p>
	<?php 
		} else {
			?>
				<p><a href="<?php echo $this->getUrl('customer/account/login') ?>" class="link-compare"><?php echo $this->__('Contact seller for this item')?></a></p>
			
			<?php
		}
	?>
	<?php } ?>
	<p><a href="<?php echo $this->getUrl('seller/rating/list', array('id' => $_product->getSellerId())); ?>"><?php echo $this->__('View Seller Store')?></a></p>
	</div>
</div>
