<div class="block seller-sidebar">
	<div class="block-title">
		<strong>
			<span><?php echo $this->__('Seller Details'); ?></span>
		</strong>
	</div>
	<div class="block-content">
	<?php
	$_product = Mage::getModel('catalog/product')->load(Mage::registry('current_product')->getId());
	if ($_product->getSellerId())
	{
		$seller = Mage::getModel('customer/customer')->load($_product->getSellerId());
		$write = Mage::getSingleton('core/resource')->getConnection('core_write');
		$readresult=$write->query("SELECT ((SUM(`item_desc`) + SUM(`price`) + SUM(`ship`) + SUM(`communication`)) / count(*)) / 5 as sellerfeedback from jordanshopper_feedback_seller where seller_id = " . $_product->getSellerId());
		$sellerFeedback = $readresult->fetch();
		$sellerFeedback = ceil($sellerFeedback['sellerfeedback']);
		$orderCount = Mage::getModel('sales/order')->getCollection()
		->addFieldToFilter('customer_id', array('eq' => $_product->getSellerId()))
		->getSize();
			
		?>
	<div style="width: 200px;">
		<h2>
			<?php echo $seller->getName();?>
			<span style="color: red; font-size: 14px"><a
				href="<?php echo $this->getUrl('seller/rating/list', array('id' => $_product->getSellerId())) ?>">(<?php echo $orderCount ?>)
			</a>
			</span>
		</h2>
	</div>
	<div style="width: 200px;">
		<span class="rating"> <?php for($feedback=0; $feedback < $sellerFeedback; $feedback++) { ?>
			<input type="radio"
			class="rating-input validate-one-required-by-name"
			id="rating-input-1-5-<?php echo $_product->getId() ?>"
			name="<?php echo $_product->getId() ?>" value="5" checked="checked"
			disabled> <label
			for="rating-input-1-5-<?php echo $_product->getId() ?>"
			class="rating-star"></label> <?php } ?>
		</span>
	</div>
	<?php } ?>
	<p><a href="<?php echo $this->getUrl('seller/rating/list/id/1'); ?>"><?php echo $this->__('View Seller Store')?></a></p>
	</div>
</div>
