<form action="<?php echo $this->getUrl('seller/index/sellerPost') ?>" method="post" id="form-validate" enctype="multipart/form-data">
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Sell an item') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey') ?>
        <h2 class="legend"><?php echo $this->__('Item Title') ?> <em style="color:red;">*</em></h2>
        <ul class="form-list">
            <li>
                <div class="input-box">
                    <input type="hidden" name="seller_id" value="<?php echo Mage::registry('seller_id'); ?>">
                    <input type="text" name="product_title" id="title" value="" class="input-text required-entry images" />
                </div>
            </li>
        </ul>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Select Categories') ?></h2>
        <div class="input-box category">
        	<div class="parentCat">
            <?php echo $this->getCategoryTree(); ?>
            </div>
            <div class="childCat">
            	<select id="childCategory" size="10" name='category[]'>
            	</select>
            </div>
            <div class="childchildCat">
            	<select id="childchildCategory" size="10" name='category[]'>
            	</select>
            </div>
            <div class="childchildchildCat">
            	<select id="childchildchildCategory" size="10" name='category[]'>
            	</select>
            </div>
        </div>
    </div>
    
    <script>
		jQuery("select#parentCategory").on("change", function(){
				var cat_id = jQuery(this).val();
				jQuery.ajax({
					url : "<?php echo $this->getUrl('seller/index/getSubCatPost') ?>",
					type: 'post',
					data: {catid : cat_id},
					success: function(resp){
						jQuery("#childCategory").html(resp);
						jQuery("#childCategory").addClass("validate-select required-entry");
						},
					error: function(){alert('faild')}
				});
			});
		
		jQuery("select#childCategory").on("change", function(){
			var cat_id = jQuery(this).val();
			jQuery.ajax({
				url : "<?php echo $this->getUrl('seller/index/getChildChildSubCatPost') ?>",
				type: 'post',
				data: {catid : cat_id},
				success: function(resp){
					jQuery("#childchildCategory").html(resp);
					jQuery("#childchildCategory").addClass("validate-select required-entry");
					},
				error: function(){alert('faild')}
			});
		});

		jQuery("select#childchildCategory").on("change", function(){
			var cat_id = jQuery(this).val();
			jQuery.ajax({
				url : "<?php echo $this->getUrl('seller/index/getChildChildChildSubCatPost') ?>",
				type: 'post',
				data: {catid : cat_id},
				success: function(resp){
					jQuery("#childchildchildCategory").html(resp);
					jQuery("#childchildchildCategory").addClass("validate-select required-entry");
					},
				error: function(){alert('faild')}
			});
		});
    </script>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Item Subtitle') ?> <em style="color:red;">*</em></h2>
        <ul class="form-list">
            <li>
                <div class="input-box">
                    <input type="text" name="subtitle" id="subtitle" value="" class="input-text required-entry images" />
                </div>
            </li>
        </ul>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Item Condition') ?> <em style="color:red;">*</em></h2>
        <div class="input-box">
            <ul class="form-list">
                <li>
                    <input type="radio" name="item_conditions" value="new" class="radio validate-one-required-by-name" onclick="check(this.value)"/>New
                </li>
                <li>
                    <input type="radio" name="item_conditions" value="used" class="radio validate-one-required-by-name" onclick="check(this.value)"/>Used
                </li>
                <li>
                    <input type="radio" name="item_conditions" value="other" class="radio validate-one-required-by-name" onclick="check(this.value)"/>Other
                </li>
                <li>
                    <input type="text" name="item_conditions_other" id="item_conditions_other" class="condition-other input-text images required-entry" value="" style="display: none;" class="input-text " />
                </li>
            </ul>
            <script>
                        function check(value)
                        {
                            if (value == 'other')
                            {
                                $('item_conditions_other').show();
                            }
                            else
                            {
                                $('item_conditions_other').hide();
                            }
                        }
            </script>
        </div>
    </div>
    <div class="fieldset ">
        <h2 class="legend"><?php echo $this->__('Item Location'); ?> <em style="color:red;">*</em></h2>
        <ul class="form-list">
            <li>
                <div class="input-box">
                    <select id="cityselect" onchange="setCityCode(this.options[this.selectedIndex].value);
                                setCityName(this.options[this.selectedIndex].text);" name="item_location">
                        <option value="Al-sareeh">Al-sareeh</option>
                        <option value="Amman" selected="selected">Amman</option>
                        <option value="Aqaba">Aqaba</option>
                        <option value="Irbid">Irbid</option>
                        <option value="Jerash">Jerash</option>
                        <option value="Karak">Karak</option>
                        <option value="Maa'N">Maa'N</option>
                        <option value="Mafraq">Mafraq</option>
                        <option value="Ramtha">Ramtha</option>
                        <option value="Sult">Sult</option>
                        <option value="Zarqa">Zarqa</option>
                    </select>
                </div>
            </li>
        </ul>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Price & Quntity') ?> <em style="color:red;">*</em></h2>
        <ul class="form-list">
            <li>
                <div class="input-box">
                    <ul class="form-list">
                        <li>
                            <div class="add-to-cart">
                                <label for="price">Price:</label>
                                <input type="text" name="price" id="price" value="" class="input-text required-entry images" />
                                <strong>[<?php echo Mage::app()->getStore()->getBaseCurrencyCode(); ?>]</strong>
                            </div>
                        </li>
                        <li>
                            <div class="add-to-cart">
                                <label for="qty">Qty:</label>
                                <input type="text" name="qty" id="qty" value="" class="input-text required-entry images" />
                            </div>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Delivery') ?> <em style="color:red;">*</em></h2>
        <div class="input-box">
            <ul class="form-list">
                <li>
                    <input type="radio" name="delivery_details" value="none" class="radio validate-one-required-by-name" onclick="delivery(this.value)"/>None
                </li>
                <li>
                    <input type="radio" name="delivery_details" value="free" class="radio validate-one-required-by-name" onclick="delivery(this.value)"/>Free
                </li>
                <li>
                    <input type="radio" name="delivery_details" value="charge" class="radio validate-one-required-by-name" onclick="delivery(this.value)"/>Delivery Charge
                </li>
                <li>
                    <input type="text" name="delivery_cost" id="delivery_cost" class="images required-entry input-text" style="display: none;"/>
                </li>
            </ul>
        </div>
        <script>
                            function delivery(value)
                            {
                                if (value == "charge")
                                {
                                    $('delivery_cost').show();
                                }
                                else
                                {
                                    $('delivery_cost').hide();
                                }
                            }
        </script>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Payment Method') ?> <em style="color:red;">*</em></h2>
        <div class="input-box">
            <ul class="form-list">
                <li>
                    <input type="radio" name="payment_method" value="1" class="radio validate-one-required-by-name" onclick="payment(this.value)"/>Cash On Delivery
                </li>
                <li>
                    <input type="radio" name="payment_method" value="2" class="radio validate-one-required-by-name" onclick="payment(this.value)"/>Paypal
                </li>
                <li>
                    <input type="text" name="paypal_email" id="paypal_email" class="paypal_email input-text images required-entry" value="" style="display: none;" class="input-text " />
                </li>
            </ul>
        </div>
        <script>
                            function payment(value)
                            {
                                if (value == "2")
                                {
                                    $('paypal_email').show();
                                }
                                else
                                {
                                    $('paypal_email').hide();
                                }
                            }
        </script>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Upload Images') ?></h2>
        <ul class="form-list">
            <li>
                <div class="image-box" id="inp">
                    <input type="file" name="images[]" id="file" class="required-file images"> <button type="button" value="add more" onclick="createNewUpload()">+</button>
                </div>
            </li>
        </ul>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Description') ?><em style="color:red;"> *</em></h2>
        <ul class="form-list">
            <li>
                <div class="input-box desc">
                    <textarea name="description" class="jqte-test required-entry"></textarea>                	
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p class="back-link"><a href="<?php echo Mage::getUrl('seller/index'); ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
    </div>
</form>
<script>
                            jQuery('.jqte-test').jqte();

                            // settings of status
                            var jqteStatus = true;
                            jQuery(".status").click(function()
                            {
                                jqteStatus = jqteStatus ? false : true;
                                jQuery('.jqte-test').jqte({"status": jqteStatus})
                            });
</script>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    var dyname = 1;
    function createNewUpload() {
       // if (dyname >= 10)
        //{
          //  alert("<?php //echo $this->__('The Limit upload of images is 2')?>");
        //}
        //else
        //{
        dyname = dyname + 1;
        var input = document.createElement('input');
        input.type = "file";
        input.name = "images[]";
        input.id = "upload" + (dyname + 1);
        input.className = "images";
        document.getElementById('inp').appendChild(input);
        var input = document.createElement('input');
        input.type = "button";
        input.name = "images[]";
        input.value = "-";
        input.id = "upload" + (dyname + 1);
        input.className = "upload" + (dyname + 1);
        input.setAttribute("onclick","javascript:removeInput(this.className);");
        document.getElementById('inp').appendChild(input);
       // }
    }

    function removeInput(val)
    {
    	document.getElementById(val).remove();
    	document.getElementById(val).remove();
    }
    
</script>
