<div class="page-title title-buttons">
    <h1><?php echo $this->__('Seller Dashboard') ?></h1>
    <button type="button" title="<?php echo $this->__('Sell an item') ?>" class="button" onclick="window.location='<?php echo Mage::getUrl('seller/index/add'); ?>';"><span><span><?php echo $this->__('Sell an item') ?></span></span></button>
</div>
<div class="seller-dashboard top">
	<div class="total-seller first">
		<h4><?php echo $this->__('Total Saved Items'); ?></h4>
		<h1>250 Items</h1>
	</div>
	<div class="total-seller">
		<h4><?php echo $this->__('Total Submited Items'); ?></h4>
		<h1>30 Items</h1>
	</div>
</div>
<div class="seller-dashboard bottom">
	<div class="total-seller first">
		<h4><?php echo $this->__('Total Wating Approval'); ?></h4>
		<h1>10 Items</h1>
	</div>
	<div class="total-seller">
		<h4><?php echo $this->__('Total Sold Items'); ?></h4>
		<h1>5 Items</h1>
	</div>
</div>