<script src="http://js.nicedit.com/nicEdit-latest.js" type="text/javascript"></script>
<script type="text/javascript">
    bkLib.onDomLoaded(function() { nicEditors.allTextAreas() });
</script>
<?php 
$item = $this->getItem();
?>
<form action="<?php echo $this->getUrl('seller/item/editPost') ?>" method="post" id="form-validate" enctype="multipart/form-data">
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Sell an item') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey') ?>
        <h2 class="legend"><?php echo $this->__('Item Title') ?> <em style="color:red;">*</em></h2>
        <ul class="form-list">
            <li>
                <div class="input-box">
                    <input type="hidden" name="item_id" value="<?php echo $item->getId(); ?>">
                    <input type="text" name="product_title" id="title" value="<?php echo $item->getProductTitle(); ?>" class="input-text images" />
                </div>
            </li>
        </ul>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Select Categories') ?></h2>
        <div class="input-box category">
        	<div class="parentCat">
            <?php echo $this->getCategoryTree(); ?>
            </div>
            <div class="childCat">
            	<select id="childCategory" size="10" name='category[]'>
            	</select>
            </div>
            <div class="childchildCat">
            	<select id="childchildCategory" size="10" name='category[]'>
            	</select>
            </div>
            <div class="childchildchildCat">
            	<select id="childchildchildCategory" size="10" name='category[]'>
            	</select>
            </div>
        </div>
    </div>
    
    <script>
		jQuery("select#parentCategory").on("change", function(){
				var cat_id = jQuery(this).val();
				jQuery.ajax({
					url : "<?php echo $this->getUrl('seller/index/getSubCatPost') ?>",
					type: 'post',
					data: {catid : cat_id},
					success: function(resp){
						if(resp)
						{
						jQuery("#childCategory").html(resp);
						jQuery("#childCategory").addClass("validate-select required-entry");
						}
						else
						{
							jQuery("#childCategory").html(resp);
							jQuery("#childCategory").removeClass("validate-select required-entry");
						}
						},
					error: function(){alert('faild')}
				});
			});
		
		jQuery("select#childCategory").on("change", function(){
			var cat_id = jQuery(this).val();
			jQuery.ajax({
				url : "<?php echo $this->getUrl('seller/index/getChildChildSubCatPost') ?>",
				type: 'post',
				data: {catid : cat_id},
				success: function(resp){
					if(resp)
					{
					jQuery("#childchildCategory").html(resp);
					jQuery("#childchildCategory").addClass("validate-select required-entry");
					}
					else
					{
						jQuery("#childchildCategory").html(resp);
						jQuery("#childchildCategory").removeClass("validate-select required-entry");
					}
					},
				error: function(){alert('faild')}
			});
		});

		jQuery("select#childchildCategory").on("change", function(){
			var cat_id = jQuery(this).val();
			jQuery.ajax({
				url : "<?php echo $this->getUrl('seller/index/getChildChildChildSubCatPost') ?>",
				type: 'post',
				data: {catid : cat_id},
				success: function(resp){
					if(resp)
					{
						jQuery("#childchildchildCategory").html(resp);
						jQuery("#childchildchildCategory").addClass("validate-select required-entry");
					}
					else
					{
						jQuery("#childchildchildCategory").html(resp);
						jQuery("#childchildchildCategory").removeClass("validate-select required-entry");
					}
					},
				error: function(){alert('faild')}
			});
		});
    </script>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Item Subtitle') ?> <em style="color:red;">*</em></h2>
        <ul class="form-list">
            <li>
                <div class="input-box">
                    <input type="text" name="subtitle" id="subtitle" value="<?php echo $item->getProductSubtitle(); ?>" class="input-text images" />
                </div>
            </li>
        </ul>
    </div>
        <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Item Condition') ?> <em style="color:red;">*</em></h2>
        <div class="input-box">
            <ul class="form-list">
                <li>
                    <input type="radio" name="item_conditions" value="3" <?php if($item->getItemConditions() == '3'){?>checked="checked"<?php }?> class="radio validate-one-required-by-name" onclick="check(this.value)"/><?php echo $this->__('New'); ?>
                </li>
                <li>
                    <input type="radio" name="item_conditions" value="5" <?php if($item->getItemConditions() == '5'){?>checked="checked"<?php }?> class="radio validate-one-required-by-name" onclick="check(this.value)"/><?php echo $this->__('Used') ?>
                </li>
                <li>
                    <input type="radio" name="item_conditions" value="4" <?php if($item->getItemConditions() == '4'){?>checked="checked"<?php }?> class="radio validate-one-required-by-name" onclick="check(this.value)"/><?php echo $this->__('Other') ?>
                </li>
                <li>
                    <input type="text" name="item_conditions_other" id="item_conditions_other" class="condition-other input-text images required-entry" value="" style="display: none;" class="input-text " />
                </li>
            </ul>
            <script>
                        function check(value)
                        {
                            if (value == '4')
                            {
                                $('item_conditions_other').show();
                            }
                            else
                            {
                                $('item_conditions_other').hide();
                            }
                        }
            </script>
        </div>
    </div>
        <div class="fieldset ">
        <h2 class="legend"><?php echo $this->__('Item Location'); ?> <em style="color:red;">*</em></h2>
        <ul class="form-list">
            <li>
            	<div class="input-box">
            		<select name="item_location" class="countryselect">
            			<option value="Worldwide" <?php if($item->getItemLocation() == 'Worldwide'){?>selected="selected"<?php } ?>><?php echo $this->__('Worldwide') ?></option>
            			<option value="Jordan" <?php if($item->getItemLocation() != 'Worldwide'){?>selected="selected"<?php } ?>><?php echo $this->__('Jordan') ?></option>
            		</select>
            	</div>
            </li>
            <li>
                <div class="input-box">
                    <select id="cityselect" onchange="setCityCode(this.options[this.selectedIndex].value);
                                setCityName(this.options[this.selectedIndex].text);" name="item_city" <?php if($item->getItemLocation() == 'Worldwide'){?> style="display:none" <?php } ?>>
                        <option value="Irbid" <?php if($item->getItemLocation() == 'Irbid'){?>selected="selected"<?php } ?>><?php echo $this->__('Irbid') ?></option>
                        <option value="Ajloun" <?php if($item->getItemLocation() == 'Ajloun'){?>selected="selected"<?php } ?>><?php echo $this->__('Ajloun') ?></option>
                        <option value="Jerash" <?php if($item->getItemLocation() == 'Jerash'){?>selected="selected"<?php } ?>><?php echo $this->__('Jerash') ?></option>
                        <option value="Mafraq" <?php if($item->getItemLocation() == 'Mafraq'){?>selected="selected"<?php } ?>><?php echo $this->__('Mafraq') ?></option>
                        <option value="Balqa" <?php if($item->getItemLocation() == 'Balqa'){?>selected="selected"<?php } ?>><?php echo $this->__('Balqa') ?></option>
                        <option value="Amman" <?php if($item->getItemLocation() == 'Amman'){?>selected="selected"<?php } ?>><?php echo $this->__('Amman') ?></option>
                        <option value="Zarqa" <?php if($item->getItemLocation() == 'Zarqa'){?>selected="selected"<?php } ?>><?php echo $this->__('Zarqa') ?></option>
                        <option value="Madaba" <?php if($item->getItemLocation() == 'Madaba'){?>selected="selected"<?php } ?>><?php echo $this->__('Madaba') ?></option>
                        <option value="Karak" <?php if($item->getItemLocation() == 'Karak'){?>selected="selected"<?php } ?>><?php echo $this->__('Karak') ?></option>
                        <option value="Tafilah" <?php if($item->getItemLocation() == 'Tafilah'){?>selected="selected"<?php } ?>><?php echo $this->__('Tafilah') ?></option>
                        <option value="Ma'an" <?php if($item->getItemLocation() == 'Ma\'an'){?>selected="selected"<?php } ?>><?php echo $this->__('Ma\'an') ?></option>
                        <option value="Aqaba" <?php if($item->getItemLocation() == 'Aqaba'){?>selected="selected"<?php } ?>><?php echo $this->__('Aqaba') ?></option>
                    </select>
                </div>
            </li>
        </ul>
    </div>
        <script>
		jQuery(".countryselect").change(function(){
			value = jQuery(".countryselect").val();
			if (value == 'Jordan')
			{
				jQuery("#cityselect").css("display","block");
			}
			else if(value == 'Worldwide')
			{
				jQuery("#cityselect").css("display","none");
			}
			});
    </script>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Price & Quntity') ?> <em style="color:red;">*</em></h2>
        <ul class="form-list">
            <li>
                <div class="input-box">
                    <ul class="form-list">
                        <li>
                            <div class="add-to-cart">
                                <label for="price"><?php echo $this->__('Price:') ?></label>
                                <input type="text" name="price" id="price" value="<?php echo $item->getPrice(); ?>" class="input-text images" />
                                <strong>[<?php echo Mage::app()->getStore()->getBaseCurrencyCode(); ?>]</strong>
                            </div>
                        </li>
                        <li>
                            <div class="add-to-cart">
                                <label for="qty"><?php echo $this->__('Qty:') ?></label>
                                <input type="text" name="qty" id="qty" value="<?php echo $item->getQty(); ?>" class="input-text images" />
                            </div>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Delivery') ?> <em style="color:red;">*</em></h2>
        <div class="input-box">
            <ul class="form-list">
                <li>
                    <input type="radio" name="delivery_details" value="none" <?php if($item->getDeliveryDetails() == 'none'){?>checked="checked"<?php }?> class="radio " onclick="delivery(this.value)"/>None
                </li>
                <li>
                    <input type="radio" name="delivery_details" value="free" <?php if($item->getDeliveryDetails() == 'free'){?>checked="checked"<?php }?> class="radio " onclick="delivery(this.value)"/>Free
                </li>
                <li>
                    <input type="radio" name="delivery_details" id="charge" value="charge" <?php if($item->getDeliveryDetails() == 'charge'){?>checked="checked"<?php }?> class="radio " onclick="delivery(this.value)"/>Delivery Charge
                </li>
                <li>
                    <input type="text" name="delivery_cost" id="delivery_cost" value="<?php echo $item->getDeliveryCost(); ?>" class="images required-entry input-text" style="display: none;"/>
                </li>
            </ul>
        </div>
        <script>
                            function delivery(value)
                            {
                                if (value == "charge")
                                {
                                    $('delivery_cost').show();
                                }
                                else
                                {
                                    $('delivery_cost').hide();
                                }
                            }
        </script>
                  <script type="text/javascript">
            jQuery(document).ready(function(){
            	if( jQuery("#charge").is(":checked")){
            		jQuery('#delivery_cost').show();
            	}
            });
            </script>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Payment Method') ?> <em style="color:red;">*</em></h2>
        <div class="input-box">
            <ul class="form-list">
                <li>
                    <input type="radio" name="payment_method" id="payment1" value="1" <?php if($item->getPaymentMethod() == 1){?>checked="checked"<?php }?> class="radio " onclick="payment(this.value)"/><?php echo $this->__('Cash On Delivery') ?>
                </li>
                <li style="display:none;">
                    <input type="radio" name="payment_method" id="payment2" value="2" <?php if($item->getPaymentMethod() == 2){?>checked="checked"<?php }?> class="radio " onclick="payment(this.value)"/><?php echo $this->__('Paypal') ?>
                </li>
                <li>
                    <input type="text" name="paypal_email" id="paypal_email" class="paypal_email input-text images required-entry" value="<?php echo $item->getPaypalEmail(); ?>" style="display: none;" class="input-text " />
                </li>
            </ul>
        </div>
        <script>
                            function payment(value)
                            {
                                if (value == 2)
                                {
                                    $('paypal_email').show();
                                }
                                else
                                {
                                    $('paypal_email').hide();
                                }
                            }
        </script>
                    <script type="text/javascript">
            jQuery(document).ready(function(){
            	if( jQuery("#payment2").is(":checked")){
            		jQuery("#paypal_email").show();
            	}
            });
            </script>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Contact Me') ?></h2>
        <ul class="form-list">
            <li>
                <div class="contact-me-div" id="contact-me-div">
                    <select name="contact-me" id="contact-me">
                    	<option <?php if($item->getContactMe()) { ?>selected="selected" <?php } ?> value="1"><?php echo $this->__('Yes'); ?></option>
                    	<option <?php if(!$item->getContactMe()) { ?>selected="selected" <?php } ?> value="0"><?php echo $this->__('No'); ?></option>
                    </select>
                </div>
            </li>
        </ul>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Upload Images') ?></h2>        
        <div style="margin: 10px">
            <?php 
            if($item->getImages()){
                $images = explode(',', $item->getImages());
                foreach ($images as $image)
                {
                	if ($image)
                	{
                    $src = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$item->getSellerId().DS.$image;                    
                    echo "<span style='display:inline-block;margin:10px'>";
                    echo '<span class="delimg"><input type="checkbox" name="delimg[]" value="' . $image . '" />' . $this->__('Delete') . '</span>';
                    echo "<img src='{$src}' height='100' width='66'>";            
                    echo "</span>";
                	}
                }
            }
            ?>
            
        </div>
        <ul class="form-list">
            <li>
                <button type="button" value="add more" onclick="createNewUpload()" style="margin-left: 200px;"><?php echo $this->__('Add New Image') ?></button>
                <div class="image-box" id="inp">
                    <input type="file" name="images[]" id="file" class="images">
                </div>
            </li>
        </ul>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Description') ?></h2>
        <ul class="form-list">
            <li>
                <div class="input-box desc">
                    <textarea name="description" id="description" class="jqte-test" style="width: 100%;"><?php echo $item->getDescription(); ?></textarea>                	
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p class="back-link"><a href="<?php echo Mage::getUrl('seller/index'); ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Update') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    var dyname = 1;
    function createNewUpload() {
        dyname = dyname + 1;
        var input = document.createElement('input');
        input.type = "file";
        input.name = "images[]";
        input.id = "upload" + (dyname + 1);
        input.className = "images";
        document.getElementById('inp').appendChild(input);
    }
</script>