<?php 
if ($this->getRequest()->getParam('id'))
{
	$sellerId = $this->getRequest()->getParam('id');
}
else
{
	$sellerId = Mage::getSingleton('customer/session')->getCustomerId();
} 
$seller = Mage::getModel('customer/customer')->load($sellerId);
$sellerRatingText = Mage::getModel('seller/feedbackseller')->getCollection()
						->addFieldToFilter('seller_id',array('eq' => $sellerId));
$sellerRatingText->getSelect()->limit(20);

//Total  Feedback Seller
$totalSellerPositive = Mage::getModel('seller/feedbackseller')->getCollection()
						->addFieldToFilter('seller_id', array('eq' => $sellerId))
						->addFieldToFilter('feedback', array('eq' => 1));
						
$totalSellerNigative = Mage::getModel('seller/feedbackseller')->getCollection()
->addFieldToFilter('seller_id', array('eq' => $sellerId))
->addFieldToFilter('feedback', array('eq' => 2));

//Total  Feedback Buyer
$totalBuyerPositive = Mage::getModel('seller/feedbackbuyer')->getCollection()
->addFieldToFilter('buyer_id', array('eq' => $sellerId))
->addFieldToFilter('feedback', array('eq' => 1));

$totalBuyerNigative = Mage::getModel('seller/feedbackbuyer')->getCollection()
->addFieldToFilter('buyer_id', array('eq' => $sellerId))
->addFieldToFilter('feedback', array('eq' => 2));

$buyerRatingTest = Mage::getModel('seller/feedbackbuyer')->getCollection()
						->addFieldToFilter('buyer_id',array('eq' => $sellerId));
$buyerRatingTest->getSelect()->limit(20);

$write = Mage::getSingleton('core/resource')->getConnection('core_write');
$readresult=$write->query("SELECT ((SUM(`item_desc`) + SUM(`price`) + SUM(`ship`) + SUM(`communication`)) / count(*)) / 5 as sellerfeedback from jordanshopper_feedback_seller where seller_id = " . $sellerId);
$sellerFeedback = $readresult->fetch();
$sellerFeedback = ceil($sellerFeedback['sellerfeedback']);

$orderCount = Mage::getModel('sales/order')->getCollection()
->addFieldToFilter('customer_id', array('eq' => $sellerId))
->getSize();

?>
<div class="block block-layered-nav">
	<div class="block-title">
			<strong>
			<span><?php echo $this->__('Seller Details')?></span>
		</strong>
	</div>
	<div class="block-content" style="background: white; margin-top: 10px;">
		<div style="width: 200px;">
					<h2><?php echo $seller->getUsername();?> : <span><?php echo $totalSellerPositive->count() + $totalSellerNigative->count() + $totalBuyerPositive->count() + $totalBuyerNigative->count() ?></span></h2>
					</div>
					<div style="width: 200px;">
					 <span class="rating">
					 <?php for($feedback=0; $feedback < $sellerFeedback; $feedback++) { ?>
						 <input type="radio" class="rating-input validate-one-required-by-name" id="rating-input-1-5" name="rate" value="5" checked="checked" disabled>
        				<label for="rating-input-1-5" class="rating-star" style="width: 16px; background: url(<?php echo $this->getSkinUrl('images/star.png')?>) 0 0px"></label>
        				<?php } ?>
        				</span>
					</div>
	</div>
</div>
<div class="block block-layered-nav">
	<div class="block-title">
		<strong>
			<span><?php echo $this->__('Rating as seller')?> <span>(<?php echo $totalSellerPositive->count() + $totalSellerNigative->count() ?>)</span></span>
		</strong>
	</div>
	<div class="block-content" style="background: white; margin-top: 10px;">
		<p><?php echo $this->__('Positive')?> <span>(<?php echo $totalSellerPositive->count() ?>)</span></p>
		<p><?php echo $this->__('Negative')?> <span>(<?php echo $totalSellerNigative->count() ?>)</span></p>
		<hr />
		<?php foreach ($sellerRatingText as $sellerRating):?>
			<p><span><img src="<?php echo $this->getSkinUrl('images/' . ($sellerRating->getFeedback() == 1 ? 'pos.png' : 'neg.png')); ?>" style="width:13px; margin: 2px;" /></span><?php echo $sellerRating->getText() ?></p>
		<?php endforeach;?>
	</div>
	<div class="block-title">
		<strong>
			<span><?php echo $this->__('Rating as buyer')?> <span>(<?php echo $totalBuyerPositive->count() + $totalBuyerNigative->count() ?>)</span></span>
		</strong>
	</div>
	<div class="block-content" style="background: white; margin-top: 10px;">
			<p><?php echo $this->__('Positive')?> <span>(<?php echo $totalBuyerPositive->count() ?>)</span></p>
		<p><?php echo $this->__('Negative')?> <span>(<?php echo $totalBuyerNigative->count() ?>)</span></p>
		<hr />
		<?php foreach ($buyerRatingTest as $buyerRating):?>
			<p><span><img src="<?php echo $this->getSkinUrl('images/' . ($buyerRating->getFeedback() == 1 ? 'pos.png' : 'neg.png')); ?>" style="width:13px; margin: 2px;" /></span><?php echo $buyerRating->getText() ?></p>
		<?php endforeach;?>
	</div>
</div>
