<?php 
if ($this->getRequest()->getParam('id'))
{
	$sellerId = $this->getRequest()->getParam('id');
}
else
{
	$sellerId = Mage::getSingleton('customer/session')->getCustomerId();
} 
$sellerRatingText = Mage::getModel('seller/feedbackseller')->getCollection()
						->addFieldToFilter('seller_id',array('eq' => $sellerId));
$sellerRatingText->getSelect()->limit(20);
$buyerRatingTest = Mage::getModel('seller/feedbackbuyer')->getCollection()
						->addFieldToFilter('buyer_id',array('eq' => $sellerId));
$buyerRatingTest->getSelect()->limit(20);
?>
<div class="block block-layered-nav">
	<div class="block-title">
		<strong>
			<span><?php echo $this->__('Rating as seller')?></span>
		</strong>
	</div>
	<div class="block-content" style="background: white; margin-top: 10px;">
		<?php foreach ($sellerRatingText as $sellerRating):?>
			<p><span><img src="<?php echo $this->getSkinUrl('images/' . ($sellerRating->getFeedback() == 1 ? 'pos.png' : 'neg.png')); ?>" style="width:13px; margin: 2px;" /></span><?php echo $sellerRating->getText() ?></p>
		<?php endforeach;?>
	</div>
	<div class="block-title">
		<strong>
			<span><?php echo $this->__('Rating as buyer')?></span>
		</strong>
	</div>
	<div class="block-content" style="background: white; margin-top: 10px;">
		<?php foreach ($buyerRatingTest as $buyerRating):?>
			<p><span><img src="<?php echo $this->getSkinUrl('images/' . ($buyerRating->getFeedback() == 1 ? 'pos.png' : 'neg.png')); ?>" style="width:13px; margin: 2px;" /></span><?php echo $buyerRating->getText() ?></p>
		<?php endforeach;?>
	</div>
</div>
