<?php 
$sellerRatingText = Mage::getModel('seller/feedbackseller')->getCollection()
						->addFieldToFilter('seller_id',array('eq' => $this->getRequest()->getParam('id')));
$sellerRatingText->getSelect()->limit(20);
$buyerRatingTest = Mage::getModel('seller/feedbackbuyer')->getCollection()
						->addFieldToFilter('buyer_id',array('eq' => $this->getRequest()->getParam('id')));
$buyerRatingTest->getSelect()->limit(20);
?>
<div class="block block-layered-nav">
	<div class="block-title">
		<strong>
			<span><?php echo $this->__('Rating as seller')?></span>
		</strong>
	</div>
	<div class="block-content" style="background: white;">
		<?php foreach ($sellerRatingText as $sellerRating):?>
			<p><span class="<?php echo ($sellerRating->getFeedback() == 1 ? 'positive' : 'negative') ?>">*</span><?php echo $sellerRating->getText() ?></p>
		<?php endforeach;?>
	</div>
	<div class="block-title">
		<strong>
			<span><?php echo $this->__('Rating as buyer')?></span>
		</strong>
	</div>
	<div class="block-content" style="background: white;">
		<?php foreach ($buyerRatingTest as $buyerRating):?>
			<p><span class="<?php echo ($buyerRating->getFeedback() == 1 ? 'positive' : 'negative') ?>">*</span><?php echo $buyerRating->getText() ?></p>
		<?php endforeach;?>
	</div>
</div>
