<div class="page-title">
    <h1><?php echo $this->__('Sell an item') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('seller/index/sellerPost') ?>" method="post" id="form-validate">
 <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo $this->__('Item Title') ?> <em style="color:red;">*</em></h2>
        <ul class="form-list">
            <li>
                <div class="input-box">
                    <input type="text" name="title" id="title" value="" class="input-text required-entry" />
                </div>
            </li>
    	</ul>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Select Categories') ?></h2>
        <ul class="form-list">
            <li>
                <div class="input-box">
                	<?php print_r($this-> getCategoryTree()); ?>
                </div>
            </li>
    	</ul>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Item Condition') ?> <em style="color:red;">*</em></h2>
      	<div class="input-box">
        <ul class="form-list">
            <li>
                	<input type="radio" name="condition" value="new" class="radio required-entry" />New
            </li>
            <li>
                	<input type="radio" name="condition" value="used" class="radio required-entry" />Used
            </li>
            <li>
                	<input type="radio" name="condition" value="other" class="radio required-entry" />Other
            </li>
    	</ul>
    	</div>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Price & Quntity') ?> <em style="color:red;">*</em></h2>
        <ul class="form-list">
            <li>
                <div class="input-box">
                	<ul class="form-list">
                		<li>
                			<div class="add-to-cart">
                				<label for="price">Price:</label>
                				<input type="text" name="price" id="price" value="" class="input-text required-entry" />
                				<strong>[<?php echo Mage::app()->getStore()->getBaseCurrencyCode(); ?>]</strong>
                			</div>
                		</li>
                		<li>
                			<div class="add-to-cart">
                				<label for="qty">Qty:</label>
                				<input type="text" name="qty" id="qty" value="" class="input-text required-entry" />
                			</div>
                		</li>
                	</ul>
                </div>
            </li>
    	</ul>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Upload Images') ?></h2>
        <ul class="form-list">
            <li>
                <div class="input-box">
                	<?php echo 'Waiting Qubbaj for his check box conditions :)'; ?>
                </div>
            </li>
    	</ul>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Description') ?></h2>
        <ul class="form-list">
            <li>
                <div class="input-box">
                	<input type="text" name="title" id="title" value="" class="input-text required-entry" />
                </div>
            </li>
    	</ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p class="back-link"><a href="<?php echo Mage::getUrl('customer/account'); ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
</script>
