<div class="page-title">
    <h1><?php echo $this->__('Sell an item') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('seller/index/sellerPost') ?>" method="post" id="form-validate">
 <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo $this->__('Item Title') ?></h2>
        <ul class="form-list">
            <li>
                <div class="input-box">
                    <input type="text" name="title" id="title" value="" class="input-text required-entry" />
                </div>
            </li>
    	</ul>
    </div>
     <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Select Categories') ?></h2>
        <ul class="form-list">
            <li>
                <div class="input-box">
                	<?php echo 'Waiting Salam\'s Code :)'; ?>
                </div>
            </li>
    	</ul>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Item Condition') ?></h2>
        <ul class="form-list">
            <li>
                <div class="input-box">
                	<?php echo 'Waiting Qubbaj for his check box conditions :)'; ?>
                </div>
            </li>
    	</ul>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Price & Quntity') ?></h2>
        <ul class="form-list">
            <li>
                <div class="input-box">
                	<?php echo 'Waiting Qubbaj for his check box conditions :)'; ?>
                </div>
            </li>
    	</ul>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Upload Images') ?></h2>
        <ul class="form-list">
            <li>
                <div class="input-box">
                	<?php echo 'Waiting Qubbaj for his check box conditions :)'; ?>
                </div>
            </li>
    	</ul>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Description') ?></h2>
        <ul class="form-list">
            <li>
                <div class="input-box">
                	<?php echo 'Waiting Qubbaj for his check box conditions :)'; ?>
                </div>
            </li>
    	</ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p class="back-link"><a href="<?php echo Mage::getUrl('customer/account'); ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
</script>