<form action="<?php echo $this->getUrl('seller/rating/buyerPost') ?>" method="post" class="f-rating" id="form-validate" enctype="multipart/form-data">
<input type="hidden" name="buyer_id" id="buyer_id" value="<?php echo $this->getRequest()->getParam('buyer_id') ?>" />
<input type="hidden" name="order_number" id="order_number" value="<?php echo $this->getRequest()->getParam('order_id') ?>" />
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Seller Rating') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <?php echo $this->getBlockHtml('formkey') ?>
<div class="fieldset">
        <?php echo $this->getBlockHtml('formkey') ?>
        <h2 class="legend"><?php echo $this->__('Feedback') ?> <em style="color:red;">*</em></h2>
        <ul class="form-list">
            <li>
                <div class="input-feedback">
                	<h3>Your feedback..</h3>
                	<style>
                	fieldset { overflow:hidden }
.some-class { float:left; clear:none; }
label { float:left; clear:none; display:block; padding: 2px 1em 0 0; }
input[type=radio], input.radio { float:left; clear:none; margin: 2px 0 0 2px; }
.form-list label {margin-left: 5px;}
                	</style>
                    <fieldset>
  <div class="some-class">
    <input type="radio" class="radio validate-one-required-by-name" name="feedback" value="1" id="feedback" />
    <label for="desc">Positive</label>
    <input type="radio" class="radio validate-one-required-by-name" name="feedback" value="2" id="feedback" />
    <label for="desc">Negative</label>   
  </div>
</fieldset>
                </div>
            </li>
        </ul>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Pay for the item') ?> <em style="color:red;">*</em></h2>
        <ul class="form-list">
            <li>
                <div class="input-feedback">
                	<h3><?php echo $this->__('How fast did the buyer pay for the item?') ?></h3>
                    <fieldset>
                    <span class="rating">
        <input type="radio" class="rating-input validate-one-required-by-name"
            id="rating-input-1-5-pay" name="pay" value="5">
        <label for="rating-input-1-5-pay" class="rating-star"></label>
        <input type="radio" class="rating-input"
            id="rating-input-1-4-pay" name="pay" value="4">
        <label for="rating-input-1-4-desc" class="rating-star"></label>
        <input type="radio" class="rating-input"
            id="rating-input-1-3-pay" name="pay" value="3">
        <label for="rating-input-1-3-pay" class="rating-star"></label>
        <input type="radio" class="rating-input"
            id="rating-input-1-2-pay" name="pay" value="2">
        <label for="rating-input-1-2-pay" class="rating-star"></label>
        <input type="radio" class="rating-input"
            id="rating-input-1-1-pay" name="pay" value="1">
        <label for="rating-input-1-1-pay" class="rating-star"></label>
    </span>
					</fieldset>
                </div>
            </li>
        </ul>
    </div>
        <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey') ?>
        <h2 class="legend"><?php echo $this->__('Buyer Communication') ?> <em style="color:red;">*</em></h2>
        <ul class="form-list">
            <li>
                <div class="input-feedback">
                	<h3><?php echo $this->__('How satisfied are you with the buyer communication?')?></h3>
         <fieldset>
                    <span class="rating">
        <input type="radio" class="rating-input"
            id="rating-input-1-5-comm" name="comm" value="5">
        <label for="rating-input-1-5-comm" class="rating-star"></label>
        <input type="radio" class="rating-input"
            id="rating-input-1-4-comm" name="comm" value="4">
        <label for="rating-input-1-4-price" class="rating-star"></label>
        <input type="radio" class="rating-input"
            id="rating-input-1-3-comm" name="comm" value="3">
        <label for="rating-input-1-3-comm" class="rating-star"></label>
        <input type="radio" class="rating-input"
            id="rating-input-1-2-comm" name="comm" value="2">
        <label for="rating-input-1-2-comm" class="rating-star"></label>
        <input type="radio" class="rating-input"
            id="rating-input-1-1-comm" name="comm" value="1">
        <label for="rating-input-1-1-comm" class="rating-star"></label>
    </span>
					</fieldset>
                </div>
            </li>
        </ul>
    </div>


                    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey') ?>
        <h2 class="legend"><?php echo $this->__('Transaction Brief') ?> <em style="color:red;">*</em></h2>
        <ul class="form-list">
            <li>
                <div class="input-feedback">
                	<h3>Write a brief description about the transaction</h3>
                	<div class="input-box desc">
                		<textarea style="width: 100%" maxlength="100" class="input-text required-entry" name="brief" id="brief"></textarea>
                	</div>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p class="back-link"><a href="<?php echo Mage::getUrl('sales/order/history'); ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
</script>