<?php
$products = $this->getSelling();
?>
<script type="text/javascript">
jQuery(function() {
	jQuery(".sellingContent").jCarouselLite({
        btnNext: ".selling-next",
        btnPrev: ".selling-prev",
        visible: 5,
    });
});
</script>
<h1><?php echo $this->__('Best Selling Products')?></h1>
<div class="div-prev">
<a href="#" class="selling-prev">&nbsp;</a>
</div>
<div class="div-next">
<a href="#" class="selling-next">&nbsp;</a>
</div>
<div class="sellingContent">
<ul id="items">
<?php
foreach ($products as $product):
$_product = Mage::getModel('catalog/product')->load($product->getId());
?>
<li>
<img width="155" src="<?php echo $_product->getImageUrl(); ?>" />
<h3 style="padding-top: 20px;"><?php echo $_product->getName(); ?></h3>
<div class="price-box">
<span class="regular-price" id="product-price-9">
<span class="price"><?php echo Mage::helper('core')->currency($_product->getPrice()); ?></span>
</span>                        
</div>
<p><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details')?></a></p>
</li>
<?php
endforeach;
?>
</ul>
</div>